### ISSUE TITLE
[Discussion] Refactor core and common packages for 6.0.0 release

### ISSUE THREAD

**Issue by BrunnerLivio** [nestjs/nest#1065]
This proposal is a summary of multiple, already submitted issues. The main focus should be, how we proceed to fix these issues (which order) so we do not implement something, which has to be refactored for another issue anyway.

## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[x] Feature request
[ ] Documentation issue or request
[x] Refactoring
</code></pre>

## Current behavior
At the moment the `core` and `common` packages provide numerous problems:

- `@nest/common` depends on `@nest/core`. [Angular handles common package like a module](https://github.com/angular/angular/blob/master/packages/common/src/common_module.ts) internally. I think we should adapt this architecture.
- `@nest/core` is too bloated. The only purpose `@nest/core` should have is the DI system. Other than that it should not have any other functionality, like handling the web server as discussed in #531. In [angular the core only depends](https://github.com/angular/angular/blob/master/packages/core/package.json) on RxJS and zone.js

## What is the motivation / use case for changing the behavior?

If these packages would get refactored, it would resolve mainly the issues #531 and #952. 
Since this is a major change, I think we should run it on a separate branch. I'd suggest start with 

- [x] Install TypeScript 3.x.x so we run on the newest version #868 
- [x] Extracting Express & Fastify from the core #531 
- [ ] Refactor the common package, so it does not depend on the core anymore and create a `CommonModule`.  #952 / #1060 
- [x] Build packages with yarn workspaces and get rid of the bundle folder #952 / #1060  / #658 

=> See [Roadmap](https://github.com/nestjs/nest/wiki/Roadmap)

While we're at it we should add a "strict" option in TsConfig. 

The new dependency architecture would look like something like this: 

![Proposed Architecture](https://i.imgur.com/0LPgO69.png)

These changes should be introduced as soon as possible. The more new features get introduced, the harder it gets to solve the named issues. That is why I propose this feature for the 6.0.0 release. 5.x.x should only introduce bug fixes, no new features until this issue is fixed

**Comment by xcaptain** [comment]
I like this proposal, I think we can get https://github.com/nestjs/nest/pull/1060 merged into branch `6.0` first and then we can discuss how to extract `express`, `fastify` stuff from `@nestjs/common`

**Comment by BrunnerLivio** [comment]
@xcaptain reading through your discussion on #1060 I thought it would make more trouble because of the circular dependency:

>current package structure comes with some problems [...] Code circular dependencies, @nestjs/common depends and @nestjs/core and @nestjs/core depends @nestjs/common

So I thought we should first refactor common/core. But as it seems you already resolved it, so I think it would make sense merge #1060 first, so we have solid ground for the other issues.

**Comment by shekohex** [comment]
that's what @wbhob proposed a year ago i think, when nest was `v4`.

so yeah, we should make a plan to work on. make a use of GitHub `projects` to track the progress and open PRs, we all here to help.

**Comment by wbhob** [comment]
I'd be thrilled to help in any way I can. @kamilmysliwiec I think Nest has hit a critical enough mass to think about forming a small team of maintainers, rather than taking on the whole project yourself.

**Comment by BrunnerLivio** [comment]
@wbhob I second this! As @shekohex mentioned we should start using milestone & project feature of Github so contributors know hows the scope of the next release. In addition I think we should start a better way of communicating so the maintainer team can coordinate better.

**Comment by wbhob** [comment]
Slack would be particularly good for the maintenance team @BrunnerLivio – since it's a smaller group, it wouldn't get cluttered as easily.

I spoke with Kamil about a year ago about joining the core team (it was at about 1k stars at that point) but like I said I'd love to be a part of the team and start getting involved with Nest again.

**Comment by yharaskrik** [comment]
I second @wbhob even though I'm just starting to get into contributing to Nest.

**Comment by jkchao** [comment]
Hi guys, i think we should change the `noImplicitAny` options in `tsconfg.json`, because it can make you code more secure.

**Comment by BrunnerLivio** [comment]
I was thinking about how we can approach the platform problems. NestJS does not have any platforms implemented as Angular does in the background. 

FYI: I am currently investigating and clarifying with the Angular team what a platform actually is: https://github.com/angular/angular/issues/27096

Was this left out on purpose? @kamilmysliwiec 

May we consider a similar structure for 
- `@nestjs/core`: https://github.com/angular/angular/blob/4c2ce4e8ba4c5ac5ce8754d67bc6603eaad4564a/packages/core/src/platform_core_providers.ts
- `@nestjs/platform-express`:  https://github.com/angular/angular/blob/master/packages/platform-browser/src/browser.ts#L47

This would replace `addCoreInjectables` of the module class:
https://github.com/nestjs/nest/blob/master/packages/core/injector/module.ts#L101

Because these `coreInjectables` will get provided by the `corePlatform`.

Please correct me if I confused anything.

**Comment by marcus-sa** [comment]
Nest should be stripped apart so only the architecture is left.
From there on you should create a module for each platform.

Example
https://github.com/marcus-sa/nest/tree/feat/one/examples/platform-express/src

**Comment by marcus-sa** [comment]
@jkchao `strict` option should be turned on, not just `noImplicitAny`

**Comment by neilime** [comment]
In my opinion, refactoring express and fastify dedicated code as real adapters (https://en.wikipedia.org/wiki/Adapter_pattern) is very important. 

For the moment nest/core is too linked (hardcoded) with express and fastify, but actual express and fastify adapters are not the same interface.

It makes it more complex to use an adapter other than express, and the code is heavier.

I'm in to help to solve this, is there already a branch to work on it ?

**Comment by BrunnerLivio** [comment]
@neilime not yet.. Trying to initiate a new branch with https://github.com/nestjs/nest/pull/1307 :)

**Comment by neilime** [comment]
Here is a code base of what I have in mind : https://github.com/nestjs/nest/compare/master...neilime:real-adapters

**Comment by DanielSchaffer** [comment]
Hello all -- I'm pretty new to Nest, and my reason for being here in mainly due to the fact that I'd starting making a similar framework on my own (https://github.com/dandi-mvc/dandi) before realizing that Nest existed. It seems like it'd make far more sense for me to contribute my efforts here than to trying to keep a separate solution going. I'm not familiar with Nest yet, but it sounds like by coincidence, I set my project up very similarly to what you folks are looking to do here, as far as separating the features into separate packages. To give a brief summary of what I did:

 - **core**: only includes types and classes specific to dependency injection. Depends on common.
 - common: Additional utility classes and types, such as a "disposable" implementation, simple error handling utilities, a class implementation for UUIDs, and a cross-platform proxy for the URL class
 - **mvc**: The MVC portion of the framework is designed to be used as effectively a configuration layer on top of an existing server framework. While I wrote it with the intention of building it on top of  express, it could, in theory be used with any similar server framework. To enable this, there are several different services that abstract the required functionality:
   - RouteGenerator: generates the array of routes defined by decorator metadata
   - RouteMapper: registers the routes with the server framework
   - RouteInitializer: registers per-request DI objects, checks defined authorization conditions
   - RouteHandler: invokes the controller, handles any response object transformation, sets response content
   - RouteExecutor: oversees init and handling, provides request-level error handling 
 - **mvc-express**: Express-specific implementation of RouteMapper, DI bootstrapper implementation that starts the express server

I was pretty aggressive about dividing the various responsibilities into separate packages, and interfaces/services within the packages, and it has afforded a great level of flexibility for implementing the other features of the framework.

**Comment by BrunnerLivio** [comment]
From my point of view, this issue can be seen as resolved. 6.0.0 brought most of the proposed changes with it in some form. If you still see some points of the discussion as unresolved, create a new issue. It will be easier to track!

**Comment by wbhob** [comment]
nice to know that this _finally_ landed after my suggestion a couple years back.
